name: .NET Core Desktop

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: windows-latest
    name: Dotnet Build
    
    steps:
      # - name: Install 7Zip PowerShell Module
      #   shell: powershell
#        run: Install-Module 7Zip4PowerShell -Force -Verbose
#       - uses: actions/checkout@v2
#       - name: Setup dotnet
#         uses: actions/setup-dotnet@v1
#         with:
#           dotnet-version: '3.1.101'
      - run: powershell curl https://github.com/MichalStrehovsky/bflat/releases/download/v0.0.2/bflat-0.0.2-win64.zip -o bflat.zip
      - run: powershell Expand-Archive -Path .\bflat.zip -DestinationPath .\bflat
      #- run: dotnet publish -c Release --runtime win-x64
      - run: powershell .\bflat\bflat.exe build $env:GITHUB_WORKSPACE\Program.cs --os:windows
      #- run: zip -q -r bin\Release\netcoreapp3.1\DotNetDllPathPatcherWPF.zip 
      - run: powershell New-Item -Path '$env:GITHUB_WORKSPACE\bin\Release\bflat' -ItemType Directory
      - run: powershell Move-Item 'Program.exe' '$env:GITHUB_WORKSPACE\bin\Release\bflat'
      - run: powershell Move-Item 'Program.pdb' '$env:GITHUB_WORKSPACE\bin\Release\bflat'
      - run: powershell Compress-7Zip $env:GITHUB_WORKSPACE\bin\Release\bflat -ArchiveFileName "ASUS_BIOS_Replace.zip" -Format Zip
      - run: powershell Compress-Archive -Path $env:GITHUB_WORKSPACE\bin\Release\bflat -DestinationPath "ASUS_BIOS_Replace.zip"
      - name: Create a Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "ASUS_BIOS_Replace.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
        
